// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYBUeZgsyOrax5qydwr9gU51ujgfOvNcA',
    appId: '1:217267921710:web:fba6e001b498b903a7d0bf',
    messagingSenderId: '217267921710',
    projectId: 'local-rush-6e90c',
    authDomain: 'local-rush-6e90c.firebaseapp.com',
    storageBucket: 'local-rush-6e90c.firebasestorage.app',
    measurementId: 'G-V5VGNCGQYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJhuHPbwRkswIdcZexzrOeXCgjNA9WF8g',
    appId: '1:217267921710:android:90210f530e43cefaa7d0bf',
    messagingSenderId: '217267921710',
    projectId: 'local-rush-6e90c',
    storageBucket: 'local-rush-6e90c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMtLMXxuWHGRBmiwdMzjwjfMIKjkkTr6k',
    appId: '1:217267921710:ios:b2759419002d7fc0a7d0bf',
    messagingSenderId: '217267921710',
    projectId: 'local-rush-6e90c',
    storageBucket: 'local-rush-6e90c.firebasestorage.app',
    iosBundleId: 'com.example.localRush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMtLMXxuWHGRBmiwdMzjwjfMIKjkkTr6k',
    appId: '1:217267921710:ios:b2759419002d7fc0a7d0bf',
    messagingSenderId: '217267921710',
    projectId: 'local-rush-6e90c',
    storageBucket: 'local-rush-6e90c.firebasestorage.app',
    iosBundleId: 'com.example.localRush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYBUeZgsyOrax5qydwr9gU51ujgfOvNcA',
    appId: '1:217267921710:web:da519853b5397634a7d0bf',
    messagingSenderId: '217267921710',
    projectId: 'local-rush-6e90c',
    authDomain: 'local-rush-6e90c.firebaseapp.com',
    storageBucket: 'local-rush-6e90c.firebasestorage.app',
    measurementId: 'G-5J9XRQ8D0J',
  );
}
